// Generated by CoffeeScript 1.7.1
var Authorize_Url, Comment, EventProxy, Inte, Lots, Noconcern, Topic, User, Warehouse, config, crypto, fs, helper, https, path, plugs, url;

fs = require('fs');

path = require('path');

crypto = require('crypto');

EventProxy = require('eventproxy');

config = require('../config').config;

https = require('https');

url = require('url');

plugs = require('./wechat-plugs');

helper = require("../lib/helper");

User = require('../model/mongo').User;

Inte = require('../model/mongo').Inte;

Lots = require('../model/mongo').Lots;

Warehouse = require('../model/mongo').Warehouse;

Topic = require('../model/mongo').Topic;

Comment = require('../model/mongo').Comment;

Authorize_Url = "https://open.weixin.qq.com/connect/oauth2/authorize?appid=" + config.APPID + "&redirect_uri={url}&response_type=code&scope=snsapi_userinfo&state={state}#wechat_redirect";

Noconcern = "http://mp.weixin.qq.com/s?__biz=MzA5MTUwMzMyNA==&mid=200560267&idx=1&sn=ff18fdd9bbf0efe2dde9ccc8d3028fb4#rd";

exports.addlot = function(req, res, next) {
  return Lots.getLots(function(err, list) {
    return res.render("admin/addlot", {
      list: list
    });
  });
};

exports.postaddlot = function(req, res, next) {
  var a, list, re, _i, _len;
  re = new helper.recode();
  console.log(req.params.lot_type);
  list = req.body.lots.split("\r\n");
  for (_i = 0, _len = list.length; _i < _len; _i++) {
    a = list[_i];
    if ((a != null) && a !== "") {
      Warehouse.newlot(req.params.lot_type, a, function(err, lot) {});
    }
  }
  return res.send(re);
};
