// Generated by CoffeeScript 1.7.1
var Comment, models;

models = require('./base');

Comment = models.Comment;

exports.getByTopic = function(tid, callback) {
  return Comment.find({
    topic: tid
  }).sort({
    _id: -1
  }).limit(200).exec(callback);
};

exports.getByTime = function(tid, startime, callback) {
  return Comment.find({
    topic: tid
  }).sort({
    create_at: -1
  }).limit(200).exec(callback);
};

exports.newComment = function(uid, topic, name, content, callback) {
  var l;
  l = new Comment();
  l.uid = uid;
  l.topic = topic;
  l.name = name;
  l.content = content;
  return l.save(callback);
};
