// Generated by CoffeeScript 1.7.1
var TopicLot, models;

models = require('./base');

TopicLot = models.TopicLot;

exports.getTopiclotList = function(callback) {
  return TopicLot.find({}, callback);
};

exports.getTopiclot = function(uid, callback) {
  return TopicLot.find({
    uid: uid
  }, callback);
};

exports.newtopiclot = function(nickname, uid, callback) {
  var lot;
  lot = new TopicLot();
  lot.nickname = nickname;
  lot.uid = uid;
  return lot.save(callback);
};
