// Generated by CoffeeScript 1.7.1
var Topic, models;

models = require('./base');

Topic = models.Topic;

exports.getOne = function(callback) {
  var st;
  st = new Date();
  return Topic.findOne({
    start_at: {
      $lt: new Date()
    },
    end_at: {
      $gte: new Date()
    }
  }, callback);
};

exports.getById = function(id, callback) {
  return Topic.findOne({
    _id: id
  }, callback);
};

exports.getTopic = function(callback) {
  return Topic.find({}).sort({
    order: -1
  }).exec(callback);
};

exports.newTopic = function(name, description, lot, prelot, startime, endtime, callback) {
  var l;
  l = new Topic();
  l.name = name;
  l.description = description;
  l.lot = lot;
  l.prelot = prelot;
  l.start_at = startime;
  l.end_at = endtime;
  return l.save(callback);
};
