// Generated by CoffeeScript 1.7.1
var Warehouse, models;

models = require('./base');

Warehouse = models.Warehouse;

exports.getByUserId = function(id, lid, callback) {
  return Warehouse.findOne({
    usedby: id,
    info: lid
  }, callback);
};

exports.getById = function(id, callback) {
  return Warehouse.findOne({
    _id: id
  }, callback);
};

exports.getOne = function(id, callback) {
  return Warehouse.findOne({
    info: id,
    used: false
  }, callback);
};

exports.setBy = function(uid, id, callback) {
  return Warehouse.findOne({
    usedby: uid,
    _id: id
  }, callback);
};

exports.newlot = function(info, content, callback) {
  var l;
  l = new Warehouse();
  l.info = info;
  l.content = content;
  return l.save(callback);
};
