// Generated by CoffeeScript 1.7.1

/*
--------------------------------------------
     Begin index.coffee
--------------------------------------------
 */
var Inte, InteSchema, Lot, LotSchema, Lots, LotsSchema, ObjectId, Schema, UserSchema, config, mongoose;

mongoose = require('mongoose');

config = require('../../../config').config;

Schema = mongoose.Schema;

ObjectId = Schema.ObjectId;

mongoose.connect(config.mdb, function(err) {
  if (err) {
    console.error('Connect to %s error: %s', config.mdb, err.message);
    return process.exit(1);
  }
});


/*
--------------------------------------------
     Begin user.coffee
--------------------------------------------
 */

UserSchema = new Schema({
  openid: {
    type: String,
    index: true
  },
  nickname: {
    type: String
  },
  sex: {
    type: Number,
    "default": 0
  },
  province: {
    type: String
  },
  country: {
    type: String
  },
  headimgurl: {
    type: String
  },
  active: {
    type: Boolean,
    "default": false
  },
  update_at: {
    type: Date,
    "default": new Date()
  },
  create_at: {
    type: Date,
    "default": new Date()
  }
});

mongoose.model('User', UserSchema);

exports.User = mongoose.model('User');


/*
--------------------------------------------
     Begin inte.coffee
--------------------------------------------
 */

InteSchema = new Schema({
  openid: {
    type: String,
    index: true
  },
  inte: {
    type: Number
  },
  only: {
    type: String
  },
  action: {
    type: String
  },
  create_at: {
    type: Date,
    "default": new Date()
  }
});

Inte = mongoose.model('Inte', InteSchema);

exports.Inte = Inte;


/*
--------------------------------------------
     Begin lots.coffee
--------------------------------------------
 */

LotsSchema = new Schema({
  name: {
    type: String
  },
  description: {
    type: String
  },
  img: {
    type: String
  },
  order: {
    type: Number
  },
  inte: {
    type: Number
  },
  create_at: {
    type: Date,
    "default": new Date()
  }
});

Lots = mongoose.model('Lots', LotsSchema);

exports.Lots = Lots;


/*
--------------------------------------------
     Begin warehouse.coffee
--------------------------------------------
 */

LotSchema = new Schema({
  info: {
    type: ObjectId
  },
  content: {
    type: String
  },
  used: {
    type: Boolean,
    "default": false
  },
  usedby: {
    type: ObjectId,
    rel: "user"
  },
  used_at: {
    type: Date
  },
  create_at: {
    type: Date,
    "default": new Date()
  }
});

Lot = mongoose.model('Lot', LotSchema);

exports.Lot = Lot;
